release:
  version: 3.1.1
  release_notes: /releases/3-1-1
  download_tarball: https://github.com/PintaProject/Pinta/releases/download/3.1.1/pinta-3.1.1.tar.gz
  download_osx: https://github.com/PintaProject/Pinta/releases/download/3.1.1/Pinta-macos-x86_64.dmg
  download_macosarm64: https://github.com/PintaProject/Pinta/releases/download/3.1.1/Pinta-macos-arm64.dmg
  download_win: https://github.com/PintaProject/Pinta/releases/download/3.1.1/Pinta-x86_64.exe
  download_zip: https://github.com/PintaProject/Pinta/releases/download/3.1.1/pinta-3.1.1.zip

links:
  bugs: https://github.com/PintaProject/Pinta/issues
  suggestions: https://github.com/PintaProject/Pinta/discussions/categories/ideas
  questions: https://github.com/PintaProject/Pinta/discussions/categories/q-a
  discussions: https://github.com/PintaProject/Pinta/discussions/categories/general
  translations: https://hosted.weblate.org/engage/pinta/
